name: Package

on:
  push:
    branches: edited

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Environments
        run: |
          echo ::set-env name=SM_VERSION::1.10
      
      - name: SourceMod
        run: |
          bash scripts/sourcemod.sh
      
      - name: Install
        run: |
          bash scripts/install.sh
      
      - name: Set Version
        run: |
          bash scripts/date.sh
      
      - name: Compile
        run: |
          bash scripts/compile.sh
      
      - name: Package
        run: |
          bash scripts/package.sh
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@master
        with:
          name: FF2-Library-${{env.DATE_VERSION}}
          path: ./build/package